name: Release Workflow

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.12.2'

      - name: Install Dependencies
        run: npm install

      - name: Build dist
        run: npm run-script build

      - name: Create Release ZIP
        run: npm run-script release

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: referral-link-inserter.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
